### ISSUE TITLE
Change style for checkbox

### ISSUE THREAD

**Issue by erikttv** [hovedstyret/indok-web#312]
Checkbox has a different color than the standardized colors. Need to change to a more consistent color with regards to the current website. 
![image](https://user-images.githubusercontent.com/56157771/139300642-1e23c185-8642-4abe-a362-1ae11d70ba5c.png)

**Comment by MorganFH** [comment]
The issue here is that the checkbox defaults to checked color `secondary` instead of `primary`. We currently use Material UI v4.

Material UI v4 docs: default color is `secondary`
https://v4.mui.com/api/checkbox/#props

Material UI v5 docs: default color is `primary`
https://mui.com/components/checkboxes/#color

So this will be fixed once we update to material v5 (another reason to address #290)
